{{- if .Values.route.enabled -}}
{{- $fullName := include "starter-kit.fullname" . -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ $fullName }}
spec:
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None
{{- end }}